- op: replace 
  path: /metadata/name 
  value: proxy-to-all 
- op: replace  
  path: /spec/selector/matchLabels/app
  value: proxy-to-all 
- op: replace  
  path: /spec/template/metadata/labels/app
  value: proxy-to-all
- op: replace  
  path: /spec/template/spec/containers/0/name
  value: proxy-to-all 
- op: replace 
  path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
  value: proxy-to-all-cm